// dynamic metadat/ tab title
export async function generateMetadata({ params }) {
  const { slug } = await params;
  return {
    title: ` Blog ${slug}`,
  };
}
//++++++ donot use  both at same time ++++++++++++++

// static
// export const metadata = {
//   title: "About page",
//   description: "Generated by next js app",
// };

export default async function Blog({ params }) {
  const { slug } = await params;
  return <div>Blog page {slug}</div>;
}
