// dynamic metadat/ tab title
export async function generateMetadata({ params }) {
  const { slug } = await params;
  const ogImageUrl = `http://localhost:3000/api/og?title=${encodeURIComponent(`Blog ${slug}&description=This is the blog post about ${slug}`)}`;
  return {
    title: ` Blog ${slug}`,
    openGraph: {
      images: [ogImageUrl],
    },
  };
}
//++++++ donot use  both at same time ++++++++++++++

// static
// export const metadata = {
//   title: "About page",
//   description: "Generated by next js app",
// };

export default async function Blog({ params }) {
  const { slug } = await params;
  return <div>Blog page {slug}</div>;
}
