import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="bg-gray-300 ">
          <div className="flex gap-20 font-bold ">
            <Link
              href={"/"}
              className="block  p-5  hover:bg-gray-500 hover:text-white"
            >
              Home
            </Link>
            <Link
              className="block  p-5  hover:bg-gray-500 hover:text-white"
              href={"/signin"}
            >
              Sign In
            </Link>
            <Link
              className="block  p-5  hover:bg-gray-500 hover:text-white"
              href={"/signup"}
            >
              Sign Up
            </Link>
            <Link
              className="block  p-5  hover:bg-gray-500 hover:text-white"
              href={"/dashboard"}
            >
              Dashboard
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
