export const items = [
  {
    id: 1,
    name: "Urban Runner Pro",
    category: "Footwear",
    description: "Lightweight comfort for every stride, day or night.",
    price: 23.55,
    originalPrice: 35.0,
    emoji: "👟",
    badge: "New",
    colors: [
      { name: "emerald", bg: "bg-emerald-500", ring: "ring-emerald-500" },
      { name: "rose", bg: "bg-rose-400", ring: "ring-rose-400" },
      { name: "indigo", bg: "bg-indigo-500", ring: "ring-indigo-500" },
    ],
  },
  {
    id: 2,
    name: "Classic Leather Bag",
    category: "Accessories",
    description: "Timeless design meets everyday functionality.",
    price: 59.99,
    originalPrice: 80.0,
    emoji: "👜",
    badge: "Sale",
    colors: [
      { name: "amber", bg: "bg-amber-500", ring: "ring-amber-500" },
      { name: "stone", bg: "bg-stone-500", ring: "ring-stone-500" },
      { name: "black", bg: "bg-gray-900", ring: "ring-gray-900" },
    ],
  },
  {
    id: 3,
    name: "Slim Fit Jacket",
    category: "Clothing",
    description: "Stay sharp and warm whatever the weather throws at you.",
    price: 89.0,
    originalPrice: 120.0,
    emoji: "🧥",
    badge: "Hot",
    colors: [
      { name: "sky", bg: "bg-sky-500", ring: "ring-sky-500" },
      { name: "slate", bg: "bg-slate-600", ring: "ring-slate-600" },
      { name: "red", bg: "bg-red-500", ring: "ring-red-500" },
    ],
  },
  {
    id: 4,
    name: "Sport Sunglasses",
    category: "Eyewear",
    description: "UV protection with a sleek aerodynamic frame.",
    price: 34.0,
    originalPrice: 50.0,
    emoji: "🕶️",
    badge: "New",
    colors: [
      { name: "black", bg: "bg-gray-900", ring: "ring-gray-900" },
      { name: "brown", bg: "bg-yellow-800", ring: "ring-yellow-800" },
      { name: "blue", bg: "bg-blue-500", ring: "ring-blue-500" },
    ],
  },
  {
    id: 5,
    name: "Casual Wrist Watch",
    category: "Accessories",
    description: "Minimal dial, maximum style for any occasion.",
    price: 120.0,
    originalPrice: 160.0,
    emoji: "⌚",
    badge: "Popular",
    colors: [
      { name: "gold", bg: "bg-yellow-400", ring: "ring-yellow-400" },
      { name: "silver", bg: "bg-gray-300", ring: "ring-gray-300" },
      { name: "rose", bg: "bg-rose-400", ring: "ring-rose-400" },
    ],
  },
  {
    id: 6,
    name: "Wireless Headphones",
    category: "Electronics",
    description: "Crystal clear sound with 30-hour battery life.",
    price: 75.0,
    originalPrice: 110.0,
    emoji: "🎧",
    badge: "Sale",
    colors: [
      { name: "black", bg: "bg-gray-900", ring: "ring-gray-900" },
      { name: "white", bg: "bg-gray-100", ring: "ring-gray-300" },
      { name: "purple", bg: "bg-purple-500", ring: "ring-purple-500" },
    ],
  },
];
