import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Logout from "@/components/Logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="max-w-7xl bg-gray-200 mx-auto p-5 flex gap-10">
          <Link href={"/"}>Home</Link>
          <Link href={"/auth/signup"}>Sign Up</Link>
          <Link href={"/auth/signin"}>Sign In</Link>
          <Link href={"/dashboard"}>Dashboard</Link>
          <Logout />
        </div>
        {children}
      </body>
    </html>
  );
}
