export const metadata = {
  title: {
    default: "auth | chai or code",
    template: "%s | cahi or code",
    absolute: "",
  },
  description: "generated by next app",
};
export default function AuthLayout({ children }) {
  return <div>{children}</div>;
}
